In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

print("Libraries imported successfully!")

Libraries imported successfully!


# New Section

# New Section

In [ ]:
# 1. Load dataset
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

# 2. Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Train Model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# 4. Evaluate
y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

print("=== Task 1: Random Forest Results ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

=== Task 1: Random Forest Results ===
Accuracy: 0.9649122807017544

Confusion Matrix:
 [[40  3]
 [ 1 70]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

ROC-AUC Score: 0.9952505732066819


In [ ]:
# 1. Load Pima Diabetes Dataset
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
cols = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome",
]
df_diabetes = pd.read_csv(url, names=cols)

# 2. Clean unrealistic 0 values
zero_cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
df_diabetes[zero_cols] = df_diabetes[zero_cols].replace(0, np.nan)
df_diabetes.fillna(df_diabetes.median(), inplace=True)

# 3. Split dataset
X = df_diabetes.drop("Outcome", axis=1)
y = df_diabetes["Outcome"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Train Logistic Regression
lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train_scaled, y_train)

# 6. Evaluate
y_pred = lr_model.predict(X_test_scaled)
y_prob = lr_model.predict_proba(X_test_scaled)[:, 1]

print("=== Task 2: Logistic Regression Results ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

# 7. Coefficients
coef_df = pd.DataFrame(
    {"Feature": X.columns, "Coefficient": lr_model.coef_[0]}
).sort_values(by="Coefficient", ascending=False)
print("\nModel Coefficients:\n", coef_df)

=== Task 2: Logistic Regression Results ===
Accuracy: 0.7532467532467533

Confusion Matrix:
 [[82 17]
 [21 34]]

Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154

ROC-AUC Score: 0.82277318640955

Model Coefficients:
                     Feature  Coefficient
1                   Glucose     1.102682
5                       BMI     0.688839
7                       Age     0.392410
0               Pregnancies     0.222978
6  DiabetesPedigreeFunction     0.203635
3             SkinThickness     0.068836
4                   Insulin    -0.138252
2             BloodPressure    -0.151540


In [ ]:
# 1. Load Titanic dataset
titanic_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df_titanic = pd.read_csv(titanic_url)

# 2. Select & clean features
df_titanic = df_titanic[
    ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Survived"]
]
df_titanic["Sex"] = df_titanic["Sex"].map({"male": 0, "female": 1})
df_titanic["Age"].fillna(df_titanic["Age"].median(), inplace=True)

X = df_titanic.drop("Survived", axis=1)
y = df_titanic["Survived"]

# 3. Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Train XGBoost
xgb_model = XGBClassifier(
    n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42
)
xgb_model.fit(X_train_scaled, y_train)

# 6. Evaluate
y_pred = xgb_model.predict(X_test_scaled)
y_prob = xgb_model.predict_proba(X_test_scaled)[:, 1]

print("=== Task 3: XGBoost Results ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

# 7. Feature Importances
importance_df = pd.DataFrame(
    {"Feature": X.columns, "Importance": xgb_model.feature_importances_}
).sort_values(by="Importance", ascending=False)
print("\nFeature Importances:\n", importance_df)

/tmp/ipykernel_1823/4107140334.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic["Age"].fillna(df_titanic["Age"].median(), inplace=True)


=== Task 3: XGBoost Results ===
Accuracy: 0.8212290502793296

Confusion Matrix:
 [[95 10]
 [22 52]]

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.90      0.86       105
           1       0.84      0.70      0.76        74

    accuracy                           0.82       179
   macro avg       0.83      0.80      0.81       179
weighted avg       0.82      0.82      0.82       179

ROC-AUC Score: 0.8763835263835263

Feature Importances:
   Feature  Importance
1     Sex    0.612260
0  Pclass    0.207902
3   SibSp    0.067076
5    Fare    0.043055
2     Age    0.040800
4   Parch    0.028906


In [ ]:
# 1. Prepare Data
X = df_diabetes.drop("Outcome", axis=1)
y = df_diabetes["Outcome"]

# 2. Split dataset with random_state=42
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Full Decision Tree
dt_full = DecisionTreeClassifier(random_state=42)
dt_full.fit(X_train, y_train)
y_pred_full = dt_full.predict(X_test)

# 4. Restricted Decision Tree (max_depth=3)
dt_rest = DecisionTreeClassifier(max_depth=3, random_state=42)
dt_rest.fit(X_train, y_train)
y_pred_rest = dt_rest.predict(X_test)

# 5. Compare Results
print("=== Task 4: Decision Tree Comparison ===")
print("Full Tree Accuracy:", accuracy_score(y_test, y_pred_full))
print("Restricted Tree (max_depth=3) Accuracy:", accuracy_score(y_test, y_pred_rest))

print("\n--- Classification Report (Full Tree) ---")
print(classification_report(y_test, y_pred_full))

print("\n--- Classification Report (Restricted Tree) ---")
print(classification_report(y_test, y_pred_rest))

# 6. Feature Importance
feat_imp = pd.DataFrame(
    {"Feature": X.columns, "Importance": dt_rest.feature_importances_}
).sort_values(by="Importance", ascending=False)
print("\nFeature Importances (Restricted Tree):\n", feat_imp)

=== Task 4: Decision Tree Comparison ===
Full Tree Accuracy: 0.7207792207792207
Restricted Tree (max_depth=3) Accuracy: 0.7597402597402597

--- Classification Report (Full Tree) ---
              precision    recall  f1-score   support

           0       0.79      0.77      0.78        99
           1       0.60      0.64      0.62        55

    accuracy                           0.72       154
   macro avg       0.70      0.70      0.70       154
weighted avg       0.72      0.72      0.72       154


--- Classification Report (Restricted Tree) ---
              precision    recall  f1-score   support

           0       0.80      0.84      0.82        99
           1       0.68      0.62      0.65        55

    accuracy                           0.76       154
   macro avg       0.74      0.73      0.73       154
weighted avg       0.76      0.76      0.76       154


Feature Importances (Restricted Tree):
                     Feature  Importance
1                   Glucose    0.5